### ISSUE TITLE
S99 has P8 and P14

### ISSUE THREAD

**Issue by Almanzoris** [pi-base/data#621] opened 2024-04-09 17:32 UTC
It is asserted in the book Counterexamples in Topology (DOI 10.1007/978-1-4612-6290-9). Example 101 (Alexandroff Square).

In the 2nd point, it is proved that Alexandroff Square is completely normal. Consequently, it is also T5, as in the 1st point it is proved that it is T2.

**Comment by StevenClontz** [comment] 2024-04-09 20:05
![image](https://github.com/pi-base/data/assets/1559632/ab50ba80-03bc-4a62-b9e5-eb2729b2213b)

![image](https://github.com/pi-base/data/assets/1559632/7a072552-7373-41ae-a3f0-049af4ed07f2)

**Comment by Almanzoris** [comment] 2024-04-09 20:47
You're welcome! I am happy for having been able to contribute back to this great project.

And thank you for the creation of π-Base and all the work it has behind that you have put on it.

Have a great day.

**Comment by StevenClontz** [comment] 2024-04-09 21:06
No problem - this will be fixed once someone reviews #624. Please feel free to open another issue should you find another error.

**Comment by prabau** [comment] 2024-04-10 00:11
@Almanzoris @StevenClontz  There are some differences depending on the edition.  I have the Dover edition from 1995, which is an "unabridged and unaltered replication" of the Springer Verlag edition of 1978.

The General Ref Chart shows space 101 is not completely normal and not T5.  And space 101 item 3 (not item 2, line you wrote in the PR) gives an example of two subspaces that are separated, but not contained in disjoint open sets.
(If you don't have access to that, I'll reproduce it here.)

What edition do both of you have?

**Comment by StevenClontz** [comment] 2024-04-10 00:21
Hmm now that you mention it, I'm getting a sense of dejavu... I think the version I have might be the earlier edition, but it's not handy at the moment.

**Comment by Almanzoris** [comment] 2024-04-10 00:56
@prabau I am sorry... I have the edition of 1970. I do not have access to that.

**Comment by StevenClontz** [comment] 2024-04-10 01:05
Yeah, we should have noted this error in the earlier edition. It was pointed out years ago and eventually corrected, but without a note of the error. 

https://github.com/pi-base/data/blob/20ebd3653a6fed72bf26aa7d4e919dc842f5dc8b/spaces/alexandroff-square/properties/t_5.md

**Comment by StevenClontz** [comment] 2024-04-10 01:48
The error will be noted once #625 is reviewed and merged.

@Almanzoris thanks for calling this omission to our attention. I look forward to your next contribution! 😄

**Comment by prabau** [comment] 2024-04-10 04:01
@Almanzoris For information, here is item 3 for space 101 (Alexandroff square) in the second edition:

"Since $(X,\tau)$ is compact and Hausdorff, it is normal.  However, $(X,\tau)$ is not $T_5$: $A=\Delta - \\{(0,0)\\}$ and $B=\\{(x,y)|\mid x\ge 0, y=0\\}$ are clearly separated, yet they are not contained in disjoint open sets.  For let $U$ be an open set containing $B$.   Then each $(x,0)\in B$ is contained in a vertical line of height $\epsilon_x$ contained in $U$.  Since $[0,1]$ is uncountable, for some $n$ the set of $\epsilon_x$ such that $\epsilon_x>1/n$ is infinite (in fact uncountable).  Then no basis neighborhood of $(1/n,1/n)\in A$ can fail to intersect $U$."

Here $\Delta$ is the diagonal of the square.  Actually, I think there is a typo in the book.  As defined, $\overline A\cap B=\\{(0,0)\\}$, so $A$ and $B$ are not separated.  But defining $B$ as $\\{(x,y)|\mid x> 0, y=0\\}$ works fine.

**Closed** 2024-04-10 13:25 UTC

**Comment by Almanzoris** [comment] 2024-04-10 15:07
@prabau Thank you for your reply, and you are right.

@StevenClontz Thank you for your kind words.

Again, excuse me for my unintentional misinformation. I am glad that it has not gone further.

Have a great day.

**Comment by prabau** [comment] 2024-04-10 22:13
@Almanzoris Not a problem at all.  It was a good reminder for us too.  If you find anything else that should be fixed, please let us know.
