### ISSUE TITLE
Traits undecidable in ZFC

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#1118] opened 2024-12-18 06:06 UTC
This might be a duplicate, I'm not sure. I know there was issues raised about spaces which construction depends on set-theoretic axioms, this is about traits.

Currently pi-base has 3 possible values for a trait: true, false or unknown.

But for example https://topology.pi-base.org/spaces/S000003/properties/P000114

If we had a new trait, say, 'independent of ZFC', then that would help distinguish between properties which are truly unknown, and those which are known but depend on our set-theoretic assumptions.

**Comment by david20000813** [comment] 2024-12-19 20:17
I feel like this would be very useful to add, but it probably will be a lot of work for @StevenClontz.

As context for other people reading this issue: Most of the traits that are independent of ZFC will be cardinality ones - "Cardinality $=\aleph_1$" will imply "Cardinality $=\mathfrak{c}$" and "Cardinality $<\mathfrak{c}$" are independent of ZFC, "Cardinality $=\mathfrak{c}$" will imply "Cardinality $=\aleph_1$" is independent of ZFC. A more extreme case would be [S138](https://topology.pi-base.org/spaces/S000138), where "Cardinality $<\mathfrak{c}$", "Cardinality $=\mathfrak{c}$", "Cardinality $\leq\mathfrak{c}$", and "Cardinality $\leq2^\mathfrak{c}$" are all independent of ZFC. ("Cardinality $=\mathfrak{c}$" being consistent with ZFC is slightly harder to prove, but the independence of other statements is relatively easy.)

But there are also other traits that will be independent of ZFC for quite natural spaces. See https://github.com/pi-base/data/pull/1132#issuecomment-2552628868 and https://github.com/pi-base/data/pull/1132#issuecomment-2552644525, where it was noted that [S17](https://topology.pi-base.org/spaces/S000017), cocountable topology on $\mathbb{R}$, being well-based is equivalent to CH and thus independent of ZFC.

**Comment by prabau** [comment] 2024-12-19 20:35
This seems a valuable additional class of traits.

As an additional comment, we also have a few spaces that make a set-theoretic assumption beyond ZFC in their definition.  For example S148: "(CH) A Luzin subset of the reals (The generic Lusin set H)".  For those spaces, some traits that would be independent of ZFC in general are "known" due to the additional assumptions.
https://topology.pi-base.org/spaces/S000148?filter=cardinality

**Comment by StevenClontz** [comment] 2024-12-20 03:14
I agree our database should be more flexible to track results independent from ZFC. Is the proposal being able to add traits that say `value: independent` rather than `value: true` or `value: false`? If so, this issue should be moved to `pi-base/web` as it would require an update to our infrastructure, not an update to our data files in this repository.

Actually this seems to be a duplicate of #317, so I'm closing (unless I'm missing something).

**Closed by StevenClontz** 2024-12-20 03:14 UTC
Labels: trait

**Comment by StevenClontz** [comment] 2024-12-20 03:48
Thanks. Nonetheless, I think both are inherently intertwined (and any software enhancement should consider both scenarios), so it's best to have a single issue in pi-base/web to track.
